// ---------------------------------------------------------------------------
//  measurement-db — the curated evaluation-data bank that torch_measure
//  models are estimated from. The coverage totals below are AUTO-COMPUTED from
//  benchmark-cards.json (generated by
//  scripts/render_website/generate_benchmark_gallery.py),
//  so they stay in sync with the published benchmarks and never need manual
//  updating. Source of truth: the public benchmark dirs in
//  github.com/aims-foundations/measurement-db.
// ---------------------------------------------------------------------------

import benchmarkCardsRaw from "@/content/generated/benchmark-cards.json";
import modelTimelineRowsRaw from "@/content/generated/model-timeline.json";
import { hiddenBenchmarkSet } from "@/content/curated/hidden-benchmarks";

// The single point where hidden benchmarks leave the site: every card
// consumer below (shelves, coverage totals, detail-page params, chart shelf
// lists, timeline) derives from this filtered array, so a slug in
// hidden-benchmarks.ts is absent from all of them at once. The asset proxy
// enforces the same list for the underlying files.
const benchmarkCards = benchmarkCardsRaw.filter(
  (c) => !hiddenBenchmarkSet.has(c.slug),
);

// ---------------------------------------------------------------------------
//  Shelves
// ---------------------------------------------------------------------------

// A benchmark's SHELF is who produced the response value, which is a different
// question from its domain (see the note in benchmark-gallery-client.tsx: "a
// benchmark's domain is a filter, not its shelf"). Everything listed here is
// scored by a judgment — a person's, another model's, or a reward model's —
// rather than by a programmatic verifier, so the numbers carry the judge's
// disagreement as well as the subject's ability. Several also need the pairwise
// response-matrix format, which the automatic shelf never uses.
//
// Hand-maintained: benchmark-cards.json is regenerated wholesale by
// generate_benchmark_gallery.py, so a slug list here survives a rebuild where a card field
// would not. Adding a slug that isn't published is harmless — it simply won't
// match a card.
//
// This list is declared before the coverage comparison because it defines the
// scoring-provenance split between its two component rows.
export const judgedBenchmarkSlugs: readonly string[] = [
  // the response is a human rating
  "arena_140k",
  "prompt_to_leaderboard",
  "sorrybench",
  // the response is a developer's in-session acceptance of the agent's answer,
  // read off the following prompt by an LLM judge
  "swe_chat",
  // the response is an LLM judge's score
  "alpacaeval",
  "arena_hard",
  "biggen",
  "mtbench",
  "tengu",
  "wildbench",
  "writingbench",
  // the judge or reward model IS the subject under test
  "judgebench",
  "preference_dissection",
  "rewardbench",
  "rewardbench2",
];

const judgedSet = new Set(judgedBenchmarkSlugs);

// Bank totals summed from the generated per-benchmark counts. The gallery generator
// writes items + responses on every card; we just aggregate and format here.
const bankCards = benchmarkCards as ReadonlyArray<{
  slug: string;
  items: number;
  responses: number;
}>;

// The two shelves, partitioned once. `automaticCards` is the complement of the
// judged list above and the source of `automaticBenchmarkSlugs`; likewise,
// `judgedCards` drives the judgment-scored shelf's optional summary data.
const automaticCards = bankCards.filter((c) => !judgedSet.has(c.slug));
const judgedCards = bankCards.filter((c) => judgedSet.has(c.slug));

function compactCount(n: number): string {
  if (n >= 1e9) return `${(n / 1e9).toFixed(1)}B`;
  if (n >= 1e6) return `${(n / 1e6).toFixed(1)}M`;
  if (n >= 1e3) return `${Math.round(n / 1e3)}K`;
  return `${n}`;
}

export type ShelfStat = { value: string; label: string };

export type DatabaseTotal = {
  key: "benchmarks" | "items" | "subjects" | "responses";
  label: string;
  value: string;
};

function coverageCounts(cards: typeof bankCards) {
  return {
    benchmarks: `${cards.length}`,
    items: compactCount(cards.reduce((sum, card) => sum + card.items, 0)),
    responses: compactCount(
      cards.reduce((sum, card) => sum + card.responses, 0),
    ),
  };
}

/** The three headline counts for one shelf, formatted for the stat row. The
 *  response label differs per shelf because the two shelves mean different
 *  things by a "response" — a verifier's decision vs. a judgment. */
function shelfStats(
  cards: typeof bankCards,
  responseLabel: string,
): readonly ShelfStat[] {
  const counts = coverageCounts(cards);
  return [
    { value: counts.benchmarks, label: "Benchmarks curated" },
    { value: counts.items, label: "Items" },
    { value: counts.responses, label: responseLabel },
  ];
}

/** The automatically scored shelf. */
export const automaticShelfStats = shelfStats(
  automaticCards,
  "Model × item responses",
);

/** The judgment-scored shelf. */
export const judgedShelfStats = shelfStats(judgedCards, "Judged responses");

/** Bank-wide totals. Because `bankCards` has already passed through the hidden
 *  benchmark filter, these describe exactly what a visitor can browse. */
export const bankStats = shelfStats(bankCards, "Responses");

type ModelTimelineRow = { benchmarks: readonly string[] };

// model-timeline.json has one row per canonical normalized_name, the bank's
// cross-benchmark de-duplication key for named AI subjects. Intersecting each
// row's benchmark list with the visible cards counts the distinct canonically
// named AI subjects represented in the catalog. Subjects without a
// normalized_name are intentionally omitted because they cannot be reliably
// de-duplicated. Do not sum each card's `models`: that repeats systems seen in
// several benchmarks and can include human participants.
const visibleBenchmarkSet = new Set(bankCards.map((card) => card.slug));
const uniqueAiSubjectCount = (
  modelTimelineRowsRaw as ReadonlyArray<ModelTimelineRow>
).filter((subject) =>
  subject.benchmarks.some((slug) => visibleBenchmarkSet.has(slug)),
).length;
const bankCounts = coverageCounts(bankCards);

/** The four catalog-entrance totals, derived from the same checked-in website
 *  snapshot and hidden-benchmark filter as the galleries. */
export const databaseTotals: readonly DatabaseTotal[] = [
  { key: "benchmarks", value: bankCounts.benchmarks, label: "Benchmarks" },
  { key: "items", value: bankCounts.items, label: "Items" },
  {
    key: "subjects",
    value: compactCount(uniqueAiSubjectCount),
    label: "AI subjects",
  },
  { key: "responses", value: bankCounts.responses, label: "Responses" },
];

export const measurementDb = {
  title: "measurement-db",
  tagline:
    "The Measurement Data Bank is a curated exchange of item-level AI evaluation data: what each system was tested on, how it responded, and how each response was scored. Analyze those measurements with torch_measure.",
  description:
    "Discover, share, and analyze fine-grained AI measurement data with a curated item-level data bank and the torch_measure analysis package.",
  detail:
    "Coverage spans reasoning, coding, agentic, multimodal, safety, and human preference benchmarks. Every benchmark ships a reproducible build script, and each response carries its subject, item, benchmark, and test condition.",
  datasetHref:
    "https://huggingface.co/datasets/aims-foundations/measurement-db",
  repoHref: "https://github.com/aims-foundations/measurement-db",
  contributeHref:
    "https://github.com/aims-foundations/measurement-db/blob/main/CONTRIBUTING.md#adding-a-new-benchmark",
  // The measurement-db *curation* — standardized response matrices, schema, and
  // build scripts — is released under CC BY-SA 4.0. Individual benchmarks retain
  // their own upstream licenses (see each card's `license` field); this license
  // covers our contribution, not the underlying items.
  license: {
    name: "CC BY-SA 4.0",
    href: "https://creativecommons.org/licenses/by-sa/4.0/",
    summary:
      "You may share and adapt the curated data, including commercially, provided you give appropriate credit and license your derivatives under the same terms. This covers the measurement-db curation layer (standardized matrices, schema, and build scripts); individual benchmarks retain their original upstream licenses.",
  },
  // How to cite measurement-db. `bibtex` is rendered verbatim for copy-paste.
  citation: {
    text: "Nhi Truong, Sang T. Truong, and Sanmi Koyejo. measurement-db: A Curated Data Bank of AI Evaluation Results. AIMS Lab, Stanford University, 2026. https://aimslab.stanford.edu/measurement-db",
    bibtex: `@misc{measurementdb2026,
  title        = {The AI Measurement Data Bank},
  author       = {Truong, Nhi and Truong, Sang T. and Koyejo, Sanmi},
  year         = {2026},
  howpublished = {\\url{https://aimslab.stanford.edu/measurement-db}},
  note         = {AIMS Lab, Stanford University}
}`,
  },
} as const;

/** The analysis and modeling layer paired with the curated data bank. Keep
 * these public destinations together so the hero and analysis section cannot
 * drift onto different package or documentation URLs. */
export const torchMeasure = {
  title: "torch_measure",
  tagline: "A PyTorch-native toolkit for predictive evaluation of AI systems.",
  packageHref: "https://pypi.org/project/torch-measure/",
  docsHref: "https://torch-measure.readthedocs.io/en/latest/",
  repoHref: "https://github.com/aims-foundations/torch_measure",
  installCommand: "pip install torch_measure",
} as const;

// ---------------------------------------------------------------------------
//  Public benchmark gallery
// ---------------------------------------------------------------------------

// The category ids ARE the raw `domain` vocabulary from benchmarks.parquet,
// one-to-one (kept verbatim, underscores and all). Must stay in lockstep with
// DOMAIN_ORDER in scripts/render_website/generate_benchmark_gallery.py.
export type BenchmarkCategoryId =
  | "safety"
  | "cybersecurity"
  | "medicine"
  | "law"
  | "finance"
  | "mathematics"
  | "software_engineering"
  | "ml_engineering"
  | "agents_and_tool_use"
  | "science"
  | "multilingual"
  | "cultural"
  | "education"
  | "preference"
  | "reward_modeling"
  | "nlp_task"
  | "knowledge"
  | "reasoning"
  | "general";

export type Benchmark = {
  slug: string;
  name: string;
  /** Every domain this benchmark maps to, most-specific first (a benchmark can
   *  belong to several — AlgoTune is both math and coding). The first entry is
   *  its primary category, used for the accent color. */
  categories: BenchmarkCategoryId[];
  /** One-line, display-ready summary (not the raw build-script description). */
  description: string;
  license: string;
  /** Upstream code / data source. */
  code: string;
  /** Reference paper or blog post. */
  paper: string;
  /** Thumbnail under /public/benchmarks, or null to render a generated
   *  per-benchmark thumbnail. Set via benchmark-overrides.json. */
  image: string | null;
  /** How the thumbnail fills its frame: "cover" for banners/screenshots,
   *  "contain" for logos and diagrams that shouldn't be cropped. */
  fit: "cover" | "contain";
  /** Distinct subjects (models / agents / reward models) evaluated in the
   *  bank's matrix for this benchmark. Computed from the published parquet. */
  models: number;
  /** Distinct evaluation items in the bank's matrix for this benchmark. */
  items: number;
  /** Upstream release date — "YYYY-MM", "YYYY", or null when unknown. Drives
   *  the release-timeline chart. */
  releaseDate: string | null;
  /** True iff upstream released per-(model, item) responses (granularity
   *  "item" in benchmarks.parquet). Drives the "item-level responses released"
   *  tag and gallery filter; item-bank-only benchmarks (granularity
   *  "aggregate"/"not_released") carry no tag. */
  itemResponses: boolean;
  /** Optional tri-state result from benchmark_saturation.py: true = saturated,
   *  false = not saturated, null = not analyzed or inconclusive. Drives the
   *  "Saturation status" tag on cards and detail pages. */
  saturation: boolean | null;
  /** Institutions of the reference paper's first two authors (deduped), from
   *  benchmark-affiliations.json
   *  (scripts/render_website/generate_benchmark_affiliations.py).
   *  `logo` points under /public/institutions, or null → initials chip.
   *  The whole field is null until the affiliation lookup has run. */
  institutions: { name: string; logo: string | null }[] | null;
};

export type BenchmarkCategory = {
  id: BenchmarkCategoryId;
  label: string;
  blurb: string;
  /** Brand hex used for the category accent + generated thumbnails. */
  color: string;
};

// Ordered for display (matches DOMAIN_ORDER in generate_benchmark_gallery.py). Each id is a
// raw `domain` value; the label is its display name. Colors are drawn from the
// Stanford palette in app/globals.css (kept as hex so the SVG thumbnail
// generator can use them).
export const benchmarkCategories: readonly BenchmarkCategory[] = [
  {
    id: "safety",
    label: "Safety",
    blurb: "Adversarial robustness and harmful behavior refusal.",
    color: "#8c1515", // cardinal
  },
  {
    id: "cybersecurity",
    label: "Cybersecurity",
    blurb: "Offensive and defensive security capability.",
    color: "#b1040e", // bright-red
  },
  {
    id: "medicine",
    label: "Medicine",
    blurb: "Clinical and medical question answering.",
    color: "#4298b5", // sky
  },
  {
    id: "law",
    label: "Law",
    blurb: "Legal reasoning and professional domain question answering.",
    color: "#7d2b3b", // brick
  },
  {
    id: "finance",
    label: "Finance",
    blurb: "Financial reasoning, markets, and economic knowledge.",
    color: "#5f574f", // clay
  },
  {
    id: "mathematics",
    label: "Mathematics",
    blurb: "Competition-grade mathematical problem solving.",
    color: "#006cb8", // digital-blue
  },
  {
    id: "software_engineering",
    label: "Software Engineering",
    blurb: "Program synthesis and real-world software engineering.",
    color: "#175e54", // palo-alto
  },
  {
    id: "ml_engineering",
    label: "ML Engineering",
    blurb: "ML research automation, optimization, and systems benchmarks.",
    color: "#6fa287", // bay
  },
  {
    id: "agents_and_tool_use",
    label: "Agents & Tool Use",
    blurb: "Autonomous agents acting through tools and interfaces.",
    color: "#e98300", // poppy
  },
  {
    id: "science",
    label: "Science",
    blurb: "Scientific discovery, simulation, and physical-world modeling.",
    color: "#8f993e", // olive
  },
  {
    id: "multilingual",
    label: "Multilingual",
    blurb: "Reasoning and knowledge across many languages.",
    color: "#6b5b95", // indigo
  },
  {
    id: "cultural",
    label: "Cultural",
    blurb: "Region- and culture-specific knowledge and norms.",
    color: "#b3995d", // sandstone
  },
  {
    id: "education",
    label: "Education",
    blurb: "Teaching, learning, assessment, and educational content quality.",
    color: "#d1660f", // spirited
  },
  {
    id: "preference",
    label: "Preference",
    blurb: "Judged response quality and human preference.",
    color: "#008566", // digital-green
  },
  {
    id: "reward_modeling",
    label: "Reward Modeling",
    blurb: "Reward models scoring candidate responses.",
    color: "#009ab4", // aqua
  },
  {
    id: "nlp_task",
    label: "NLP Tasks",
    blurb: "Core language tasks: extraction, classification, and QA.",
    color: "#620059", // plum
  },
  {
    id: "knowledge",
    label: "Knowledge",
    blurb: "Frontier factual and world knowledge.",
    color: "#007c92", // lagunita
  },
  {
    id: "reasoning",
    label: "Reasoning",
    blurb: "Multi-step reasoning and problem solving.",
    color: "#006b81", // dark-lagunita
  },
  {
    id: "general",
    label: "General",
    blurb: "Broad, general-purpose evaluations.",
    color: "#767674", // cool-grey
  },
] as const;

// Gallery cards — GENERATED from the published parquet files by
// scripts/render_website/generate_benchmark_gallery.py (merged with the curated
// benchmark-overrides.json). Regenerate with
// `python3 scripts/render_website/generate_benchmark_gallery.py cards`. Do NOT hand-edit; change the
// overrides file (category / image / fit) instead.
export const benchmarks: readonly Benchmark[] =
  benchmarkCards as unknown as readonly Benchmark[];

/**
 * Everything scored by a programmatic verifier — the complement of
 * `judgedBenchmarkSlugs`, declared at the top of this file alongside the
 * coverage summaries that count this same shelf.
 */
export const automaticBenchmarkSlugs: readonly string[] = automaticCards.map(
  (c) => c.slug,
);

/**
 * The judged shelf as PUBLISHED — `judgedBenchmarkSlugs` filtered to the cards
 * actually in the bank. The hand list may name unpublished slugs (harmless for
 * the gallery, which simply won't match a card), but the chart pipeline treats
 * an unknown slug as a fatal coverage gap (chart-marginals.ts), so the
 * section's charts compose from this list.
 */
export const publishedJudgedBenchmarkSlugs: readonly string[] = judgedCards.map(
  (c) => c.slug,
);

// ---------------------------------------------------------------------------
//  Lookups
// ---------------------------------------------------------------------------

export function getBenchmark(slug: string): Benchmark | undefined {
  return benchmarks.find((b) => b.slug === slug);
}

export function getBenchmarkCategory(
  id: BenchmarkCategoryId,
): BenchmarkCategory | undefined {
  return benchmarkCategories.find((c) => c.id === id);
}
