// Release timeline of every model (subject) on a shelf, derived at build
// time from model-timeline.json — generated by
// scripts/render_website/generate_model_timeline.py, which aggregates the
// normalized_name / provider / release_date registry columns across every
// published benchmark's subjects.parquet in the local cache. Each row carries
// the SLUGS the model appears in, so the chart scopes to a section's shelf by
// intersecting with that shelf's slug list — re-running the script after new
// benchmarks land updates both sections' charts with no extra step.
//
// Each row's `releaseDate` is "YYYY-MM-DD" or null. The chart is a dot
// histogram: every year gets the same width, split into 12 month columns,
// and each dated model is one small dot stacked in its release month.
// Undated models are counted in a footnote under the chart rather than
// dropped silently. Dots are colored by provider: the
// companies on the shelf's Provider Coverage leaderboard each get their own
// hue, every other provider shares a neutral gray.

import modelRows from "@/content/generated/model-timeline.json";

// Colors handed to the leaderboard companies, in leaderboard-rank order.
// Distinct hues (not brand colors) so neighboring dots stay tellable.
const PROVIDER_PALETTE = [
  "#175e54", // deep teal
  "#c2410c", // burnt orange
  "#1d4ed8", // blue
  "#9333ea", // purple
  "#b91c1c", // red
  "#0e7490", // cyan
  "#a16207", // ochre
  "#be185d", // magenta
  "#4d7c0f", // olive
  "#6d28d9", // violet
  "#0f766e", // sea green
  "#92400e", // brown
  "#e11d48", // rose
  "#0284c7", // sky
  "#404040", // charcoal
] as const;
// Light enough that the long tail reads as background texture — the named
// providers are the story, and at #9ca3af the gray mass overwhelmed them.
const OTHER_COLOR = "#cfccc4";
const OTHER_LABEL = "Other";

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
] as const;

type ModelRow = {
  name: string;
  provider: string | null;
  releaseDate: string | null;
  /** Slugs of the published benchmarks this model appears in. */
  benchmarks: string[];
};

export type ModelTimelineItem = {
  name: string;
  provider: string;
  /** "Apr 2025" — month resolution; day-level registry dates are approximate. */
  released: string;
  /** "12 benchmarks" / "1 benchmark" — scoped to the shelf. */
  coverage: string;
  /** Provider accent color (top providers get hues, the tail shares gray). */
  color: string;
};

export type ModelTimelineYear = {
  /** Axis label — "2024". */
  label: string;
  /** Total dated models released this year. */
  count: number;
  /** Jan..Dec — each month's models grouped by legend entry: the pooled gray
   *  "Other" block at the bottom of the stack, then the leaderboard providers
   *  alphabetically; within a group, providers then models A→Z. */
  months: ModelTimelineItem[][];
};

export type ModelTimelineData = {
  years: ModelTimelineYear[];
  /** Tallest month stack — sizes the chart so every column fits unclipped. */
  maxMonth: number;
  legend: ReadonlyArray<{ label: string; color: string }>;
  /** First/last year on the axis. The benchmark release timeline mirrors this
   *  range so the two charts' year boundaries align vertically on the page. */
  range: { from: number; to: number };
  /** Shelf models with no month-dated release in the registry — they have no
   *  column to stand in, so they are counted in a footnote under the chart
   *  instead of being dropped silently. */
  undatedCount: number;
};

const rows = modelRows as ReadonlyArray<ModelRow>;

/** The model release timeline for one shelf. `hueCompanies` is the shelf's
 *  Provider Coverage leaderboard in rank order — hues follow it so the two
 *  charts highlight the same providers within a section. */
export function makeModelTimeline(
  slugs: readonly string[],
  hueCompanies: readonly string[],
): ModelTimelineData {
  const shelf = new Set(slugs);
  const providerColor = new Map<string, string>(
    hueCompanies
      .slice(0, PROVIDER_PALETTE.length)
      .map((c, i) => [c, PROVIDER_PALETTE[i]]),
  );

  type Parsed = ModelTimelineItem & {
    date: string;
    year: number;
    month: number;
  };
  const parsed: Parsed[] = [];
  let undatedCount = 0;
  for (const r of rows) {
    const onShelf = r.benchmarks.reduce(
      (n, s) => n + (shelf.has(s) ? 1 : 0),
      0,
    );
    if (onShelf === 0) continue;
    const m = /^(\d{4})-(\d{2})/.exec(r.releaseDate ?? "");
    if (!m) {
      undatedCount += 1;
      continue;
    }
    parsed.push({
      name: r.name,
      provider: r.provider ?? OTHER_LABEL,
      date: r.releaseDate!,
      year: Number(m[1]),
      month: Number(m[2]),
      released: `${MONTHS[Number(m[2]) - 1]} ${m[1]}`,
      coverage: `${onShelf} benchmark${onShelf === 1 ? "" : "s"}`,
      color: (r.provider && providerColor.get(r.provider)) ?? OTHER_COLOR,
    });
  }
  parsed.sort(
    (a, b) => a.date.localeCompare(b.date) || a.name.localeCompare(b.name),
  );

  if (parsed.length === 0) {
    return {
      years: [],
      maxMonth: 1,
      legend: [],
      range: { from: 0, to: 0 },
      undatedCount,
    };
  }

  const range = {
    from: Math.min(...parsed.map((p) => p.year)),
    to: Math.max(...parsed.map((p) => p.year)),
  };

  const item = ({
    name,
    provider,
    released,
    coverage,
    color,
  }: Parsed): ModelTimelineItem => ({
    name,
    provider,
    released,
    coverage,
    color,
  });

  const years: ModelTimelineYear[] = [];
  for (let year = range.from; year <= range.to; year++) {
    const months: ModelTimelineItem[][] = Array.from({ length: 12 }, () => []);
    for (const p of parsed)
      if (p.year === year) months[p.month - 1].push(item(p));
    // Sort by legend group — the whole gray tail pooled as "Other" at the
    // bottom of the stack, then the hued providers alphabetically — so each
    // column shows contiguous color blocks. Dots keep their exact provider
    // for the tooltip.
    const isOther = (it: ModelTimelineItem) => it.color === OTHER_COLOR;
    for (const m of months)
      m.sort(
        (a, b) =>
          Number(isOther(b)) - Number(isOther(a)) ||
          a.provider.localeCompare(b.provider, "en", { sensitivity: "base" }) ||
          a.name.localeCompare(b.name),
      );
    years.push({
      label: String(year),
      count: months.reduce((n, m) => n + m.length, 0),
      months,
    });
  }

  return {
    years,
    maxMonth: Math.max(
      1,
      ...years.flatMap((y) => y.months.map((m) => m.length)),
    ),
    legend: [
      ...[...providerColor.entries()].map(([label, color]) => ({
        label,
        color,
      })),
      { label: OTHER_LABEL, color: OTHER_COLOR },
    ],
    range,
    undatedCount,
  };
}

export const modelTimelineMeta = {
  title: "AI Subject Release Timeline",
  description:
    "Dated AI subjects evaluated in the data bank, stacked by release month and colored by provider.",
} as const;
