"use client";

import { useState } from "react";
import { createPortal } from "react-dom";

import { useMobileLatestScroll } from "@/components/use-mobile-latest-scroll";
import type {
  ModelTimelineData,
  ModelTimelineItem,
} from "@/content/model-timeline";

// Dot-histogram release timeline: every year gets the same width, split into
// 12 month columns, and each dated model in the bank is one small dot stacked
// in its release month — so column height reads as releases per month. Dots
// are colored by provider (legend above the chart) and carry a hover tooltip
// with the model's name, provider, release month and benchmark coverage.
// Derived entirely from model-timeline.json (see content/model-timeline.ts),
// regenerated by generate_model_timeline.py.

// Sized generously — the chart lives folded inside an accordion, so its
// footprint costs nothing until a reader asks for it. 8 axis years at this
// pitch stay inside the container without a horizontal scrollbar.
const DOT = 7; // px dot diameter
const HIT = 12; // px touch target around the visual dot
const GAP = 1; // px between stacked dots
const PITCH = HIT + GAP;
const MONTH_W = HIT; // one non-overlapping target per month column
const YEAR_W = MONTH_W * 12;

type Tip = { item: ModelTimelineItem; x: number; y: number };

export function ModelTimeline({ data }: { data: ModelTimelineData }) {
  const [tip, setTip] = useState<Tip | null>(null);
  const scrollRef = useMobileLatestScroll(data.years.length);

  const chartH = data.maxMonth * PITCH;

  return (
    <div className="panel w-fit max-w-full px-4 py-6 sm:px-6 sm:py-8">
      {/* Provider legend — the hues assigned in content/model-timeline.ts */}
      <div className="mb-5 flex flex-wrap gap-x-4 gap-y-1.5">
        {data.legend.map((l) => (
          <span key={l.label} className="flex items-center gap-1.5">
            <span
              className="h-2 w-2 shrink-0 rounded-full"
              style={{ backgroundColor: l.color }}
            />
            <span className="text-[11px] leading-none text-[var(--muted)]">
              {l.label}
            </span>
          </span>
        ))}
      </div>

      <p className="mb-2 text-[11px] leading-relaxed text-[var(--muted)] lg:hidden">
        Showing recent releases. Swipe for earlier years.
      </p>
      <div
        ref={scrollRef}
        className="snap-x snap-proximity overflow-x-auto focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--digital-blue)]"
        tabIndex={0}
        aria-label="AI subject release timeline; recent years shown first on narrow screens"
      >
        <div className="flex" style={{ width: "max-content" }}>
          {data.years.map((y) => (
            <div
              key={y.label}
              className="snap-end border-l border-[var(--line)]"
              style={{ width: YEAR_W }}
            >
              {/* 12 month columns of bottom-anchored dot stacks */}
              <div className="flex items-end" style={{ height: chartH }}>
                {y.months.map((models, mi) => (
                  <div
                    key={mi}
                    className="flex flex-col-reverse items-center"
                    style={{ width: MONTH_W, gap: GAP }}
                  >
                    {models.map((it) => {
                      const move = (e: React.MouseEvent) =>
                        setTip({ item: it, x: e.clientX, y: e.clientY });
                      const touch = (e: React.TouchEvent) => {
                        const point = e.touches[0];
                        if (point)
                          setTip({
                            item: it,
                            x: point.clientX,
                            y: point.clientY,
                          });
                      };
                      return (
                        <span
                          key={it.name}
                          role="img"
                          aria-label={`${it.name}, ${it.provider}, released ${it.released}, evaluated in ${it.coverage}`}
                          className="group flex shrink-0 cursor-help items-center justify-center rounded-full"
                          style={{
                            width: HIT,
                            height: HIT,
                          }}
                          onMouseEnter={move}
                          onMouseMove={move}
                          onMouseLeave={() => setTip(null)}
                          onTouchStart={touch}
                          onTouchMove={touch}
                        >
                          <span
                            className="shrink-0 rounded-full opacity-80 group-hover:opacity-100"
                            style={{
                              width: DOT,
                              height: DOT,
                              backgroundColor: it.color,
                            }}
                            aria-hidden
                          />
                        </span>
                      );
                    })}
                  </div>
                ))}
              </div>

              {/* Axis — the year + its count */}
              <div className="border-t border-[var(--line)] pt-1.5 text-center">
                <span className="font-mono text-[10px] leading-none text-[var(--muted)]">
                  {y.label} · {y.count}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Exclusions, said out loud: a chart that bounds its coverage and
          doesn't say so reads as complete. */}
      {data.undatedCount > 0 ? (
        <p className="mt-4 text-[11px] leading-relaxed text-[var(--muted)]">
          {data.undatedCount} AI subject
          {data.undatedCount === 1 ? "" : "s"} with no recorded release date{" "}
          {data.undatedCount === 1 ? "is" : "are"} not shown.
        </p>
      ) : null}

      {/* Cursor-following tooltip, portaled to <body> so `position: fixed`
          resolves against the viewport despite transformed ancestors
          (ScrollReveal) — same trick as the heatmap. */}
      {tip && typeof document !== "undefined"
        ? createPortal(
            <div
              className="pointer-events-none fixed z-50 max-w-xs rounded-md bg-[var(--ink)] px-2.5 py-1.5 text-xs leading-snug text-[var(--white)] shadow-lg"
              style={{
                top: tip.y + 16,
                left: tip.x + 14,
                transform:
                  tip.x > window.innerWidth - 280
                    ? "translateX(calc(-100% - 28px))"
                    : undefined,
              }}
            >
              <p className="font-semibold">{tip.item.name}</p>
              <p className="mt-0.5 opacity-85">
                {tip.item.provider} · Released {tip.item.released}
              </p>
              <p className="opacity-85">Evaluated in {tip.item.coverage}</p>
            </div>,
            document.body,
          )
        : null}
    </div>
  );
}
